# Pre-build: turn the bootloader's firmware.hex into src/bl_image.h
# (a 2 KB PROGMEM image of 0x7800-0x7FFF, padded with 0xFF).
Import("env")

import os

BL_START = 0x7800
BL_SIZE = 0x800
SPM_ENTRY = 0x7FE0
# do_spm() prologue: movw r30,r24 / movw r0,r20 / sts SPMCSR,r22 / spm
SPM_ENTRY_SIG = bytes([0xFC, 0x01, 0x0A, 0x01, 0x60, 0x93, 0x57, 0x00, 0xE8, 0x95])
# Version record (MBBP_BL_INFO_ADDR): 'M' 'B' 'B' 'L' <version> <~version>
BL_INFO = 0x7FF8
BL_INFO_MAGIC = b"MBBL"

project_dir = env.subst("$PROJECT_DIR")
hex_path = os.path.normpath(os.path.join(project_dir, env.GetProjectOption("custom_bl_hex")))
out_path = os.path.join(project_dir, "src", "bl_image.h")

if not os.path.isfile(hex_path):
    raise SystemExit("gen_bl_image: %s not found - build the bootloader project first" % hex_path)

image = bytearray([0xFF] * BL_SIZE)
base = 0
with open(hex_path) as f:
    for line in f:
        line = line.strip()
        if not line.startswith(":"):
            continue
        rec = bytes.fromhex(line[1:])
        if sum(rec) & 0xFF:
            raise SystemExit("gen_bl_image: bad checksum in %s" % hex_path)
        count, addr, rtype, data = rec[0], (rec[1] << 8) | rec[2], rec[3], rec[4:4 + rec[0]]
        if rtype == 0x00:
            for i, b in enumerate(data):
                a = base + addr + i
                if not BL_START <= a < BL_START + BL_SIZE:
                    raise SystemExit("gen_bl_image: data at 0x%04X is outside the boot section" % a)
                image[a - BL_START] = b
        elif rtype == 0x02:
            base = ((data[0] << 8) | data[1]) << 4
        elif rtype == 0x04:
            base = ((data[0] << 8) | data[1]) << 16

sig_off = SPM_ENTRY - BL_START
if bytes(image[sig_off:sig_off + len(SPM_ENTRY_SIG)]) != SPM_ENTRY_SIG:
    raise SystemExit("gen_bl_image: bootloader has no do_spm() at 0x%04X - refusing to build" % SPM_ENTRY)

info_off = BL_INFO - BL_START
rec = bytes(image[info_off:info_off + 6])
if rec[:4] != BL_INFO_MAGIC or (rec[4] ^ rec[5]) != 0xFF:
    raise SystemExit("gen_bl_image: bootloader has no version record at 0x%04X - rebuild it with "
                     "the .bl_info section (bootloader v2 or later)" % BL_INFO)
bl_version = rec[4]

crc = 0xFFFF
for b in image:
    crc ^= b
    for _ in range(8):
        crc = (crc >> 1) ^ 0xA001 if crc & 1 else crc >> 1

lines = [
    "/* Generated by gen_bl_image.py from %s - do not edit. */" % os.path.relpath(hex_path, project_dir).replace("\\", "/"),
    "#pragma once",
    "#include <avr/pgmspace.h>",
    "",
    "#define BL_IMAGE_CRC 0x%04X" % crc,
    "#define BL_IMAGE_VERSION %d   /* from the image's version record */" % bl_version,
    "",
    "static const uint8_t BL_IMAGE[%d] PROGMEM = {" % BL_SIZE,
]
for i in range(0, BL_SIZE, 16):
    lines.append("    " + ", ".join("0x%02X" % b for b in image[i:i + 16]) + ",")
lines += ["};", ""]
text = "\n".join(lines)

old = open(out_path).read() if os.path.isfile(out_path) else None
if text != old:
    with open(out_path, "w") as f:
        f.write(text)
print("gen_bl_image: %s -> src/bl_image.h (bootloader v%d, CRC 0x%04X)" % (hex_path, bl_version, crc))
